
import io
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

def generate_comparison_pdf(comparison_data):
    """
    Generates a PDF report comparing two regions.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*cm, bottomMargin=1*cm)
    styles = getSampleStyleSheet()
    elements = []
    
    # Styles
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=22, 
                                  spaceAfter=20, alignment=TA_CENTER, textColor=colors.HexColor('#1565c0'))
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Heading2'], fontSize=14, 
                                     spaceAfter=10, alignment=TA_CENTER, textColor=colors.grey)
    heading_style = ParagraphStyle('Heading', parent=styles['Heading2'], fontSize=16, 
                                    spaceBefore=15, spaceAfter=10, textColor=colors.HexColor('#2e7d32'))
    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, 
                                 spaceAfter=8, alignment=TA_JUSTIFY)
    
    # Title Page
    elements.append(Paragraph("Comparative Sustainability Report", title_style))
    elements.append(Paragraph("India GIS & Remote Sensing Portal", subtitle_style))
    elements.append(Spacer(1, 20))
    
    # Region Info Table
    data_a = comparison_data['region_a']
    data_b = comparison_data['region_b']
    
    info_data = [
        ['Parameter', data_a['region_name'], data_b['region_name']],
        ['Analysis Year', comparison_data['year'], comparison_data['year']],
        ['Overall USS', f"{data_a['total_uss']:.1f}/100", f"{data_b['total_uss']:.1f}/100"],
        ['Classification', data_a['classification'], data_b['classification']]
    ]
    
    t = Table(info_data, colWidths=[5*cm, 7*cm, 7*cm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e3f2fd')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))
    
    # Executive Summary directly from insights
    elements.append(Paragraph("Executive Summary", heading_style))
    elements.append(Paragraph(comparison_data['summary'], body_style))
    elements.append(Spacer(1, 15))

    # Metric Comparison Table
    elements.append(Paragraph("Detailed Metric Comparison", heading_style))
    
    metric_data = [['Module', 'Metric', data_a['region_name'], data_b['region_name'], 'Difference']]
    
    for module in comparison_data['modules']:
        res_a = data_a['results'].get(module, {})
        res_b = data_b['results'].get(module, {})
        
        val_a = res_a.get('value', 0)
        val_b = res_b.get('value', 0)
        metric_name = res_a.get('metric', '-')
        
        if isinstance(val_a, (int, float)) and isinstance(val_b, (int, float)):
            diff = val_a - val_b
            diff_str = f"{diff:+.2f}"
            val_a_str = f"{val_a:.2f}"
            val_b_str = f"{val_b:.2f}"
        else:
             diff_str = "N/A"
             val_a_str = str(val_a)
             val_b_str = str(val_b)
             
        metric_data.append([module, metric_name, val_a_str, val_b_str, diff_str])
        
    t_metrics = Table(metric_data, colWidths=[4*cm, 3*cm, 4*cm, 4*cm, 3*cm])
    t_metrics.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f5f5f5')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_metrics)
    
    # Score Comparison Chart
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Score Comparison", heading_style))
    
    chart_buf = _create_comparison_chart(data_a, data_b, comparison_data['modules'])
    if chart_buf:
        img = Image(chart_buf, width=16*cm, height=8*cm)
        elements.append(img)
    
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("Generated by India GIS Portal | Powered by GEE", 
                              ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=TA_CENTER)))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()

def _create_comparison_chart(data_a, data_b, modules):
    try:
        labels = modules
        scores_a = [data_a['results'].get(m, {}).get('score', 0) for m in modules]
        scores_b = [data_b['results'].get(m, {}).get('score', 0) for m in modules]
        
        x = np.arange(len(labels))
        width = 0.35
        
        fig, ax = plt.subplots(figsize=(10, 5))
        rects1 = ax.bar(x - width/2, scores_a, width, label=data_a['region_name'], color='#38bdf8')
        rects2 = ax.bar(x + width/2, scores_b, width, label=data_b['region_name'], color='#22c55e')
        
        ax.set_ylabel('Scores (0-25)')
        ax.set_title('Module Score Comparison')
        ax.set_xticks(x, labels)
        ax.legend()
        
        ax.bar_label(rects1, padding=3, fmt='%.1f')
        ax.bar_label(rects2, padding=3, fmt='%.1f')
        
        buf = io.BytesIO()
        plt.tight_layout()
        plt.savefig(buf, format='png', dpi=100)
        plt.close()
        buf.seek(0)
        return buf
    except Exception as e:
        print(f"Chart error: {e}")
        return None
